import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("project tooling keeps Wasm E2E portable", async () => {
  const justfile = await readFile("justfile", "utf8");
  const packageJson = JSON.parse(await readFile("package.json", "utf8"));
  const workflow = await readFile(".github/workflows/ci.yml", "utf8");
  const flyControl = await readFile("fly.control.toml", "utf8");
  const flyRuntime = await readFile("fly.runtime.toml", "utf8");
  const flyCollector = await readFile("fly.collector.toml", "utf8");
  const readme = await readFile("README.md", "utf8");
  await readFile("pnpm-lock.yaml", "utf8");

  assert.match(justfile, /node_modules\/@bytecodealliance\/jco\/lib\/wasi_snapshot_preview1\.reactor\.wasm/);
  assert.match(justfile, /^db-migrate-check:/m);
  assert.match(justfile, /^db-migrate-apply:/m);
  assert.match(justfile, /^volume-sqlite-bench:/m);
  assert.match(justfile, /^fly-volume-sqlite-bench:/m);
  assert.match(justfile, /fly_control_app := env_var_or_default\("FLY_CONTROL_APP", "mz-wasmplane-control"\)/);
  assert.match(justfile, /fly_runtime_app := env_var_or_default\("FLY_RUNTIME_APP", "mz-wasmplane-runtime"\)/);
  assert.match(justfile, /fly_collector_app := env_var_or_default\("FLY_COLLECTOR_APP", "mz-wasmplane-otel-collector"\)/);
  assert.match(justfile, /^fly-smoke:/m);
  assert.match(justfile, /^fly-smoke-production:/m);
  assert.match(justfile, /^fly-alarm-demo:/m);
  assert.match(justfile, /^fly-scale-eval:/m);
  assert.match(justfile, /^fly-scale-eval-execute:/m);
  assert.match(justfile, /^cloudflare-control-smoke:/m);
  assert.match(justfile, /^rust-daemon-bench:/m);
  assert.match(justfile, /^coverage: node-coverage rust-coverage/m);
  assert.match(justfile, /^node-coverage:/m);
  assert.match(justfile, /^rust-coverage:/m);
  assert.match(justfile, /rustup run stable cargo llvm-cov --workspace --summary-only/);
  assert.doesNotMatch(justfile, /\/Users\//);
  assert.match(packageJson.scripts["ops-smoke"], /src\/ops-smoke\.ts/);
  assert.match(packageJson.scripts["alarm-demo-smoke"], /src\/alarm-demo-smoke\.ts/);
  assert.match(packageJson.scripts["cloudflare-control-smoke"], /src\/cloudflare-control-smoke\.ts/);
  assert.match(packageJson.scripts["fly-scale-eval"], /src\/fly-scale-eval\.ts/);
  assert.match(packageJson.scripts["rust-daemon-bench"], /src\/rust-daemon-bench\.ts/);
  assert.match(packageJson.scripts.coverage, /--experimental-test-coverage/);
  assert.match(packageJson.scripts["volume-sqlite-bench"], /src\/volume-sqlite-bench\.ts/);
  assert.equal(packageJson.devDependencies["@bytecodealliance/jco"], "1.15.4");
  assert.match(workflow, /pnpm\/action-setup@v4/);
  assert.match(workflow, /cache: pnpm/);
  assert.match(workflow, /pnpm install --frozen-lockfile/);
  assert.match(workflow, /rustup target add wasm32-wasip1/);
  assert.match(workflow, /just test/);
  assert.match(workflow, /just e2e/);
  assert.match(flyControl, /app = "mz-wasmplane-control"/);
  assert.match(flyControl, /WASMPLANE_SNAPSHOT_PUBLISH_INTERVAL_MS = "5000"/);
  assert.match(flyControl, /WASMPLANE_VOLUME_SQLITE_ROOT = "\/data\/sqlite"/);
  assert.match(flyControl, /WASMPLANE_VOLUME_SQLITE_MAX_OPEN = "64"/);
  assert.match(flyControl, /WASMPLANE_VOLUME_SQLITE_MAX_PENDING_WRITES = "64"/);
  assert.match(flyControl, /WASMPLANE_VOLUME_SQLITE_MAX_BACKUPS_PER_DATABASE = "24"/);
  assert.match(flyControl, /WASMPLANE_VOLUME_SQLITE_BACKUP_RETENTION_MS = "604800000"/);
  assert.match(flyControl, /WASMPLANE_DURABLE_OBJECT_ALARM_INTERVAL_MS = "1000"/);
  assert.match(flyControl, /WASMPLANE_DURABLE_OBJECT_ALARM_NAMESPACES = "alarm-demo"/);
  assert.match(flyControl, /WASMPLANE_DURABLE_OBJECT_ALARM_WEBHOOK_URL = "https:\/\/mz-wasmplane-control\.fly\.dev\/alarm-demo\/webhook"/);
  assert.match(readme, /WASMPLANE_VOLUME_SQLITE_BACKUP_KEY_BASE64/);
  assert.match(readme, /WASMPLANE_VOLUME_SQLITE_BACKUP_KEYS_BASE64/);
  assert.match(readme, /WASMPLANE_DURABLE_OBJECT_ALARM_INTERVAL_MS/);
  assert.match(readme, /WASMPLANE_DURABLE_OBJECT_ALARM_WEBHOOK_URL/);
  assert.match(readme, /just fly-alarm-demo/);
  assert.match(readme, /just fly-scale-eval/);
  assert.match(readme, /just cloudflare-control-smoke/);
  assert.match(readme, /just rust-daemon-bench/);
  assert.match(readme, /just fly-smoke/);
  assert.match(readme, /just coverage/);
  assert.match(justfile, /--max-pending-writes 64/);
  assert.match(flyRuntime, /app = "mz-wasmplane-runtime"/);
  assert.match(flyRuntime, /RUNTIME_HOST = "::"/);
  assert.match(flyRuntime, /RUNTIME_ROUTE_SNAPSHOT_FILE = "\/data\/route-snapshot\.json"/);
  assert.match(flyRuntime, /WASMPLANE_WASIP3_HOST_DAEMON_ROUTES = "1"/);
  assert.match(flyRuntime, /WASMPLANE_WASIP3_HOST_DAEMON_WORKER_PROXY = "1"/);
  assert.match(flyRuntime, /path = "\/__runtime\/healthz"/);
  assert.match(flyCollector, /app = "mz-wasmplane-otel-collector"/);
});

test("Rust and MoonBit interop examples share a WASI p3 component contract", async () => {
  const justfile = await readFile("justfile", "utf8");
  const cargoToml = await readFile("Cargo.toml", "utf8");
  const readme = await readFile("README.md", "utf8");
  const wit = await readFile("examples/interop/wit/world.wit", "utf8");
  const rustLib = await readFile("examples/rust-interop/src/lib.rs", "utf8");
  const rustCargo = await readFile("examples/rust-interop/Cargo.toml", "utf8");
  const moonbitStub = await readFile("examples/moonbit-interop/src/probe.mbt", "utf8");
  const moonbitJustfile = await readFile("examples/moonbit-interop/justfile", "utf8");

  assert.match(wit, /package myedge:interop@0\.1\.0/);
  assert.match(wit, /world probe-world/);
  assert.match(wit, /export ping: func\(message: string\) -> string/);
  assert.match(rustCargo, /name = "rust-interop"/);
  assert.match(rustLib, /impl Guest for Component/);
  assert.match(rustLib, /fn ping\(message: String\) -> String/);
  assert.match(moonbitStub, /pub fn ping\(message : String\) -> String/);
  assert.match(moonbitJustfile, /wit-bindgen moonbit \.\.\/interop\/wit --world probe-world/);
  assert.match(justfile, /^interop-smoke:/m);
  assert.match(justfile, /wasmtime run --invoke 'ping\("hello-rust"\)'/);
  assert.match(justfile, /wasmtime run --invoke 'ping\("hello-moonbit"\)'/);
  assert.match(cargoToml, /examples\/rust-interop/);
  assert.match(readme, /## Rust and MoonBit WASI p3 interop/);
});
