[package]
name = "rust-moonbit-release-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
wasip3 = { version = "=0.9.0", features = ["async-spawn"] }
wit-bindgen = { version = "=0.62.0", features = ["async", "bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "myedge:rust-moonbit-release-worker"
