// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
// Options used:
//   * async: all
pub type Request = myedge::runtime::http::Request;
pub type Response = myedge::runtime::http::Response;
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_handle_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: i32,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();wit_bindgen::rt::async_support::start_task(async move {
  let _task_cancel = wit_bindgen::rt::async_support::TaskCancelOnDrop::new();
  let result9 = &{
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let base8 = arg4;
    let len8 = arg5;
    let mut result8 = _rt::Vec::with_capacity(len8);
    for i in 0..len8 {
      let base = base8.add(i * (4*::core::mem::size_of::<*const u8>()));
      let e8 = {
        let l2 = *base.add(0).cast::<*mut u8>();
        let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len4 = l3;
        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
        let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len7 = l6;
        let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

        myedge::runtime::types::Header{
          name: _rt::string_lift(bytes4),
          value: _rt::string_lift(bytes7),
        }
      };
      result8.push(e8);
    }
    _rt::cabi_dealloc(base8, len8 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    T::handle(myedge::runtime::http::Request{
      head: myedge::runtime::types::RequestHead{
        method: _rt::string_lift(bytes0),
        uri: _rt::string_lift(bytes1),
        headers: result8,
      },
      body: myedge::runtime::http::IncomingBody::from_handle(arg6 as u32),
    }).await
  };
  let myedge::runtime::http::Response{ head:head10, body:body10, } = result9;
  let myedge::runtime::types::ResponseHead{ status:status11, headers:headers11, } = head10;
  let vec15 = headers11;
  let len15 = vec15.len();
  let layout15 = _rt::alloc::Layout::from_size_align(vec15.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
  let (result15, _cleanup15) = wit_bindgen::rt::Cleanup::new(layout15);for (i, e) in vec15.into_iter().enumerate() {
    let base = result15.add(i * (4*::core::mem::size_of::<*const u8>()));
    {
      let myedge::runtime::types::Header{ name:name12, value:value12, } = e;
      let vec13 = name12;
      let ptr13 = vec13.as_ptr().cast::<u8>();
      let len13 = vec13.len();
      *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
      *base.add(0).cast::<*mut u8>() = ptr13.cast_mut();
      let vec14 = value12;
      let ptr14 = vec14.as_ptr().cast::<u8>();
      let len14 = vec14.len();
      *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
      *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr14.cast_mut();
    }
  }

  #[cfg(target_arch = "wasm32")]
  #[link(wasm_import_module = "[export]$root")]
  unsafe extern "C" {
    #[link_name = "[task-return]handle"]
    fn wit_import16(_: i32, _: *mut u8, _: usize, _: i32, );
  }

  #[cfg(not(target_arch = "wasm32"))]
  unsafe extern "C" fn wit_import16(_: i32, _: *mut u8, _: usize, _: i32, ) { unreachable!() }
  _task_cancel.forget();
  wit_import16(_rt::as_i32(status11), result15, len15, (body10).take_handle() as i32);
})
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __callback_handle(event0: u32, event1: u32, event2: u32) -> u32 {
  unsafe {
    wit_bindgen::rt::async_support::callback(event0, event1, event2)
  }
}
pub trait Guest {
  #[allow(async_fn_in_trait)]
  async fn handle(req: Request,) -> Response;
}
#[doc(hidden)]

macro_rules! __export_world_worker_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "[async-lift]handle")]
    unsafe extern "C" fn export_handle(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: i32,) -> i32 {
      unsafe { $($path_to_types)*::_export_handle_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6) }
    }
    #[unsafe(export_name = "[callback][async-lift]handle")]
    unsafe extern "C" fn _callback_handle(event0: u32, event1: u32, event2: u32) -> u32 {
      unsafe {
        $($path_to_types)*::__callback_handle(event0, event1, event2)
      }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_worker_cabi;
#[allow(dead_code, clippy::all)]
pub mod myedge {
  pub mod runtime {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;

      use super::super::super::_rt;
      #[derive(Clone)]
      pub struct Header {
        pub name: _rt::String,
        pub value: _rt::String,
      }
      impl ::core::fmt::Debug for Header {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Header").field("name", &self.name).field("value", &self.value).finish()
        }
      }
      #[derive(Clone)]
      pub struct RequestHead {
        pub method: _rt::String,
        pub uri: _rt::String,
        pub headers: _rt::Vec::<Header>,
      }
      impl ::core::fmt::Debug for RequestHead {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("RequestHead").field("method", &self.method).field("uri", &self.uri).field("headers", &self.headers).finish()
        }
      }
      #[derive(Clone)]
      pub struct ResponseHead {
        pub status: u16,
        pub headers: _rt::Vec::<Header>,
      }
      impl ::core::fmt::Debug for ResponseHead {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("ResponseHead").field("status", &self.status).field("headers", &self.headers).finish()
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod http {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;

      use super::super::super::_rt;
      pub type RequestHead = super::super::super::myedge::runtime::types::RequestHead;
      pub type ResponseHead = super::super::super::myedge::runtime::types::ResponseHead;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct IncomingBody{
        handle: _rt::Resource<IncomingBody>,
      }

      impl IncomingBody{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }


      unsafe impl _rt::WasmResource for IncomingBody{
        #[inline]
        unsafe fn drop(_handle: u32) {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]incoming-body"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }

          unsafe { drop(_handle as i32); }
        }
      }


      #[derive(Debug)]
      #[repr(transparent)]
      pub struct OutgoingBody{
        handle: _rt::Resource<OutgoingBody>,
      }

      impl OutgoingBody{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }


      unsafe impl _rt::WasmResource for OutgoingBody{
        #[inline]
        unsafe fn drop(_handle: u32) {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]outgoing-body"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }

          unsafe { drop(_handle as i32); }
        }
      }

      pub struct Request {
        pub head: RequestHead,
        pub body: IncomingBody,
      }
      impl ::core::fmt::Debug for Request {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Request").field("head", &self.head).field("body", &self.body).finish()
        }
      }
      pub struct Response {
        pub head: ResponseHead,
        pub body: OutgoingBody,
      }
      impl ::core::fmt::Debug for Response {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Response").field("head", &self.head).field("body", &self.body).finish()
        }
      }
      impl IncomingBody {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub async fn read(&self,max: u64,) -> Option<_rt::Vec::<u8>>{
          unsafe {

            #[derive(Copy, Clone)]
            struct ParamsLower(
            i32, i64,
            );
            unsafe impl Send for ParamsLower {}


            use wit_bindgen::rt::async_support::Subtask as _Subtask;
            struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
            #[allow(unused_parens)]
            unsafe impl<'a> _Subtask for _MySubtask<'a> {

              type Params = (&'a IncomingBody, u64, );
              type Results = Option<_rt::Vec::<u8>>;
              type ParamsLower = ParamsLower;
              fn abi_layout(&mut self) -> ::core::alloc::Layout {
                unsafe {
                  ::core::alloc::Layout::from_size_align_unchecked((3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>())
                }
              }

              fn results_offset(&mut self) -> usize { 0 }

              unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

                #[cfg(target_arch = "wasm32")]
                #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
                unsafe extern "C" {
                  #[link_name = "[async-lower][method]incoming-body.read"]
                  fn call(_: i32, _: i64, _: *mut u8, ) -> i32;
                }

                #[cfg(not(target_arch = "wasm32"))]
                unsafe extern "C" fn call(_: i32, _: i64, _: *mut u8, ) -> i32 { unreachable!() }

                unsafe { call(_params.0,_params.1,_results) as u32 }
              }

              unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
                unsafe {  }
              }
              unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
                unsafe {  }
              }
              unsafe fn params_lower(&mut self, (_lower0, _lower1,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
                unsafe {  ParamsLower((_lower0).handle() as i32, _rt::as_i64(_lower1),) }
              }
              unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
                unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u8>());

                match l0 {
                  0 => None,
                  1 => {
                    let e = {
                      let l1 = *_ptr.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l2 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len3 = l2;

                      <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l1.cast(), len3, len3))
                    };
                    Some(e)
                  }
                  _ => _rt::invalid_enum_discriminant(),
                } }
              }
            }
            _MySubtask { _unused: core::marker::PhantomData }.call((self, max,)).await
          }
        }
      }
      impl OutgoingBody {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub async fn write(&self,chunk: _rt::Vec::<u8>,) -> (){
          unsafe {

            #[derive(Copy, Clone)]
            struct ParamsLower(
            i32, *mut u8, usize,
            );
            unsafe impl Send for ParamsLower {}


            use wit_bindgen::rt::async_support::Subtask as _Subtask;
            struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
            #[allow(unused_parens)]
            unsafe impl<'a> _Subtask for _MySubtask<'a> {

              type Params = (&'a OutgoingBody, _rt::Vec::<u8>, );
              type Results = ();
              type ParamsLower = ParamsLower;
              fn abi_layout(&mut self) -> ::core::alloc::Layout {
                unsafe {
                  ::core::alloc::Layout::from_size_align_unchecked(0, 1)
                }
              }

              fn results_offset(&mut self) -> usize { 0 }

              unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

                #[cfg(target_arch = "wasm32")]
                #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
                unsafe extern "C" {
                  #[link_name = "[async-lower][method]outgoing-body.write"]
                  fn call(_: i32, _: *mut u8, _: usize, ) -> i32;
                }

                #[cfg(not(target_arch = "wasm32"))]
                unsafe extern "C" fn call(_: i32, _: *mut u8, _: usize, ) -> i32 { unreachable!() }

                unsafe { call(_params.0,_params.1,_params.2,) as u32 }
              }

              unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
                unsafe { let base0 = _params.1;
                let len0 = _params.2;
                _rt::cabi_dealloc(base0, len0 * 1, 1);
              }
            }
            unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
              unsafe { let base0 = _params.1;
              let len0 = _params.2;
              _rt::cabi_dealloc(base0, len0 * 1, 1);
            }
          }
          unsafe fn params_lower(&mut self, (_lower0, _lower1,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
            unsafe { let vec0 = <_ as Into<_rt::Vec<_>>>::into(_lower1).into_boxed_slice();
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            ::core::mem::forget(vec0);
            ParamsLower((_lower0).handle() as i32, ptr0.cast_mut(), len0,) }
          }
          unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

          }
        }
        _MySubtask { _unused: core::marker::PhantomData }.call((self, chunk,)).await
      }
    }
  }
  impl OutgoingBody {
    #[allow(unused_unsafe, clippy::all)]
    #[allow(async_fn_in_trait)]
    pub async fn finish(&self,) -> (){
      unsafe {

        #[derive(Copy, Clone)]
        struct ParamsLower(
        i32,
        );
        unsafe impl Send for ParamsLower {}


        use wit_bindgen::rt::async_support::Subtask as _Subtask;
        struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
        #[allow(unused_parens)]
        unsafe impl<'a> _Subtask for _MySubtask<'a> {

          type Params = (&'a OutgoingBody, );
          type Results = ();
          type ParamsLower = ParamsLower;
          fn abi_layout(&mut self) -> ::core::alloc::Layout {
            unsafe {
              ::core::alloc::Layout::from_size_align_unchecked(0, 1)
            }
          }

          fn results_offset(&mut self) -> usize { 0 }

          unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[async-lower][method]outgoing-body.finish"]
              fn call(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn call(_: i32, ) -> i32 { unreachable!() }

            unsafe { call(_params.0,) as u32 }
          }

          unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
            unsafe {  }
          }
          unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
            unsafe {  }
          }
          unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
            unsafe {  ParamsLower((_lower0).handle() as i32,) }
          }
          unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

          }
        }
        _MySubtask { _unused: core::marker::PhantomData }.call((self,)).await
      }
    }
  }
  #[allow(unused_unsafe, clippy::all)]
  #[allow(async_fn_in_trait)]
  pub async fn new_outgoing_body() -> OutgoingBody{
    unsafe {

      #[derive(Copy, Clone)]
      struct ParamsLower(

      );
      unsafe impl Send for ParamsLower {}


      use wit_bindgen::rt::async_support::Subtask as _Subtask;
      struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
      #[allow(unused_parens)]
      unsafe impl<'a> _Subtask for _MySubtask<'a> {

        type Params = ();
        type Results = OutgoingBody;
        type ParamsLower = ParamsLower;
        fn abi_layout(&mut self) -> ::core::alloc::Layout {
          unsafe {
            ::core::alloc::Layout::from_size_align_unchecked(4, 4)
          }
        }

        fn results_offset(&mut self) -> usize { 0 }

        unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/http@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[async-lower]new-outgoing-body"]
            fn call(_: *mut u8, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn call(_: *mut u8, ) -> i32 { unreachable!() }

          unsafe { call(_results) as u32 }
        }

        unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
          unsafe {  }
        }
        unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
          unsafe {  }
        }
        unsafe fn params_lower(&mut self, (): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
          unsafe {  ParamsLower() }
        }
        unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
          unsafe { let l0 = *_ptr.add(0).cast::<i32>();

          OutgoingBody::from_handle(l0 as u32) }
        }
      }
      _MySubtask { _unused: core::marker::PhantomData }.call(()).await
    }
  }

}


#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod kv {
  #[used]
  #[doc(hidden)]
  static __FORCE_SECTION_REF: fn() =
  super::super::super::__link_custom_section_describing_imports;

  use super::super::super::_rt;

  #[derive(Debug)]
  #[repr(transparent)]
  pub struct Namespace{
    handle: _rt::Resource<Namespace>,
  }

  impl Namespace{
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      Self {
        handle: unsafe { _rt::Resource::from_handle(handle) },
      }
    }

    #[doc(hidden)]
    pub fn take_handle(&self) -> u32 {
      _rt::Resource::take_handle(&self.handle)
    }

    #[doc(hidden)]
    pub fn handle(&self) -> u32 {
      _rt::Resource::handle(&self.handle)
    }
  }


  unsafe impl _rt::WasmResource for Namespace{
    #[inline]
    unsafe fn drop(_handle: u32) {

      #[cfg(target_arch = "wasm32")]
      #[link(wasm_import_module = "myedge:runtime/kv@0.1.0")]
      unsafe extern "C" {
        #[link_name = "[resource-drop]namespace"]
        fn drop(_: i32, );
      }

      #[cfg(not(target_arch = "wasm32"))]
      unsafe extern "C" fn drop(_: i32, ) { unreachable!() }

      unsafe { drop(_handle as i32); }
    }
  }

  #[allow(unused_unsafe, clippy::all)]
  #[allow(async_fn_in_trait)]
  pub async fn open_namespace(binding: _rt::String,) -> Option<Namespace>{
    unsafe {

      #[derive(Copy, Clone)]
      struct ParamsLower(
      *mut u8, usize,
      );
      unsafe impl Send for ParamsLower {}


      use wit_bindgen::rt::async_support::Subtask as _Subtask;
      struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
      #[allow(unused_parens)]
      unsafe impl<'a> _Subtask for _MySubtask<'a> {

        type Params = (_rt::String, );
        type Results = Option<Namespace>;
        type ParamsLower = ParamsLower;
        fn abi_layout(&mut self) -> ::core::alloc::Layout {
          unsafe {
            ::core::alloc::Layout::from_size_align_unchecked(8, 4)
          }
        }

        fn results_offset(&mut self) -> usize { 0 }

        unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/kv@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[async-lower]open-namespace"]
            fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32 { unreachable!() }

          unsafe { call(_params.0,_params.1,_results) as u32 }
        }

        unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
          unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
        }
      }
      unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
      }
    }
    unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
      unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
      let ptr0 = vec0.as_ptr().cast::<u8>();
      let len0 = vec0.len();
      ::core::mem::forget(vec0);
      ParamsLower(ptr0.cast_mut(), len0,) }
    }
    unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
      unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u8>());

      match l0 {
        0 => None,
        1 => {
          let e = {
            let l1 = *_ptr.add(4).cast::<i32>();

            Namespace::from_handle(l1 as u32)
          };
          Some(e)
        }
        _ => _rt::invalid_enum_discriminant(),
      } }
    }
  }
  _MySubtask { _unused: core::marker::PhantomData }.call((binding,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn get(ns: &Namespace,key: _rt::String,) -> Option<_rt::Vec::<u8>>{
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    i32, *mut u8, usize,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (&'a Namespace, _rt::String, );
      type Results = Option<_rt::Vec::<u8>>;
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked((3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>())
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/kv@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]get"]
          fn call(_: i32, _: *mut u8, _: usize, _: *mut u8, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: i32, _: *mut u8, _: usize, _: *mut u8, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,_params.1,_params.2,_results) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.1, _params.2, 1);
      }
    }
    unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
      unsafe { _rt::cabi_dealloc(_params.1, _params.2, 1);
    }
  }
  unsafe fn params_lower(&mut self, (_lower0, _lower1,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
    unsafe { let vec0 = (_lower1.into_bytes()).into_boxed_slice();
    let ptr0 = vec0.as_ptr().cast::<u8>();
    let len0 = vec0.len();
    ::core::mem::forget(vec0);
    ParamsLower((_lower0).handle() as i32, ptr0.cast_mut(), len0,) }
  }
  unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
    unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u8>());

    match l0 {
      0 => None,
      1 => {
        let e = {
          let l1 = *_ptr.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len3 = l2;

          <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l1.cast(), len3, len3))
        };
        Some(e)
      }
      _ => _rt::invalid_enum_discriminant(),
    } }
  }
}
_MySubtask { _unused: core::marker::PhantomData }.call((ns, key,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn put(ns: &Namespace,key: _rt::String,value: _rt::Vec::<u8>,ttl_seconds: Option<u64>,) -> (){
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    *mut u8,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (&'a Namespace, _rt::String, _rt::Vec::<u8>, Option<u64>, );
      type Results = ();
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked((24+4*::core::mem::size_of::<*const u8>()), 8)
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/kv@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]put"]
          fn call(_: *mut u8, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: *mut u8, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe { let l0 = *_params.0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l1 = *_params.0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
        let l2 = *_params.0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l3 = *_params.0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base4 = l2;
        let len4 = l3;
        _rt::cabi_dealloc(base4, len4 * 1, 1);
      }
    }
    unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
      unsafe { let l0 = *_params.0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l1 = *_params.0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l0, l1, 1);
      let l2 = *_params.0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l3 = *_params.0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base4 = l2;
      let len4 = l3;
      _rt::cabi_dealloc(base4, len4 * 1, 1);
    }
  }
  unsafe fn params_lower(&mut self, (_lower0, _lower1, _lower2, _lower3,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
    let _param_ptr = unsafe { _ptr.add(0) };
    unsafe { *_param_ptr.add(0).cast::<i32>() = (_lower0).handle() as i32;
  }
  let _param_ptr = unsafe { _ptr.add(::core::mem::size_of::<*const u8>()) };
  unsafe { let vec0 = (_lower1.into_bytes()).into_boxed_slice();
  let ptr0 = vec0.as_ptr().cast::<u8>();
  let len0 = vec0.len();
  ::core::mem::forget(vec0);
  *_param_ptr.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len0;
  *_param_ptr.add(0).cast::<*mut u8>() = ptr0.cast_mut();
}
let _param_ptr = unsafe { _ptr.add((3*::core::mem::size_of::<*const u8>())) };
unsafe { let vec0 = <_ as Into<_rt::Vec<_>>>::into(_lower2).into_boxed_slice();
let ptr0 = vec0.as_ptr().cast::<u8>();
let len0 = vec0.len();
::core::mem::forget(vec0);
*_param_ptr.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len0;
*_param_ptr.add(0).cast::<*mut u8>() = ptr0.cast_mut();
}
let _param_ptr = unsafe { _ptr.add((8+4*::core::mem::size_of::<*const u8>())) };
unsafe { match _lower3 {
  Some(e) => {
    *_param_ptr.add(0).cast::<u8>() = (1i32) as u8;
    *_param_ptr.add(8).cast::<i64>() = _rt::as_i64(e);
  },
  None => {
    {
      *_param_ptr.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
}; }
ParamsLower(_ptr,)
}
unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

}
}
_MySubtask { _unused: core::marker::PhantomData }.call((ns, key, value, ttl_seconds,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn delete(ns: &Namespace,key: _rt::String,) -> (){
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    i32, *mut u8, usize,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (&'a Namespace, _rt::String, );
      type Results = ();
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked(0, 1)
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/kv@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]delete"]
          fn call(_: i32, _: *mut u8, _: usize, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: i32, _: *mut u8, _: usize, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,_params.1,_params.2,) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.1, _params.2, 1);
      }
    }
    unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
      unsafe { _rt::cabi_dealloc(_params.1, _params.2, 1);
    }
  }
  unsafe fn params_lower(&mut self, (_lower0, _lower1,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
    unsafe { let vec0 = (_lower1.into_bytes()).into_boxed_slice();
    let ptr0 = vec0.as_ptr().cast::<u8>();
    let len0 = vec0.len();
    ::core::mem::forget(vec0);
    ParamsLower((_lower0).handle() as i32, ptr0.cast_mut(), len0,) }
  }
  unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

  }
}
_MySubtask { _unused: core::marker::PhantomData }.call((ns, key,)).await
}
}

}


#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod secrets {
  #[used]
  #[doc(hidden)]
  static __FORCE_SECTION_REF: fn() =
  super::super::super::__link_custom_section_describing_imports;

  use super::super::super::_rt;

  #[derive(Debug)]
  #[repr(transparent)]
  pub struct Secret{
    handle: _rt::Resource<Secret>,
  }

  impl Secret{
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      Self {
        handle: unsafe { _rt::Resource::from_handle(handle) },
      }
    }

    #[doc(hidden)]
    pub fn take_handle(&self) -> u32 {
      _rt::Resource::take_handle(&self.handle)
    }

    #[doc(hidden)]
    pub fn handle(&self) -> u32 {
      _rt::Resource::handle(&self.handle)
    }
  }


  unsafe impl _rt::WasmResource for Secret{
    #[inline]
    unsafe fn drop(_handle: u32) {

      #[cfg(target_arch = "wasm32")]
      #[link(wasm_import_module = "myedge:runtime/secrets@0.1.0")]
      unsafe extern "C" {
        #[link_name = "[resource-drop]secret"]
        fn drop(_: i32, );
      }

      #[cfg(not(target_arch = "wasm32"))]
      unsafe extern "C" fn drop(_: i32, ) { unreachable!() }

      unsafe { drop(_handle as i32); }
    }
  }

  #[allow(unused_unsafe, clippy::all)]
  #[allow(async_fn_in_trait)]
  pub async fn open_secret(binding: _rt::String,) -> Option<Secret>{
    unsafe {

      #[derive(Copy, Clone)]
      struct ParamsLower(
      *mut u8, usize,
      );
      unsafe impl Send for ParamsLower {}


      use wit_bindgen::rt::async_support::Subtask as _Subtask;
      struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
      #[allow(unused_parens)]
      unsafe impl<'a> _Subtask for _MySubtask<'a> {

        type Params = (_rt::String, );
        type Results = Option<Secret>;
        type ParamsLower = ParamsLower;
        fn abi_layout(&mut self) -> ::core::alloc::Layout {
          unsafe {
            ::core::alloc::Layout::from_size_align_unchecked(8, 4)
          }
        }

        fn results_offset(&mut self) -> usize { 0 }

        unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/secrets@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[async-lower]open-secret"]
            fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32 { unreachable!() }

          unsafe { call(_params.0,_params.1,_results) as u32 }
        }

        unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
          unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
        }
      }
      unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
      }
    }
    unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
      unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
      let ptr0 = vec0.as_ptr().cast::<u8>();
      let len0 = vec0.len();
      ::core::mem::forget(vec0);
      ParamsLower(ptr0.cast_mut(), len0,) }
    }
    unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
      unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u8>());

      match l0 {
        0 => None,
        1 => {
          let e = {
            let l1 = *_ptr.add(4).cast::<i32>();

            Secret::from_handle(l1 as u32)
          };
          Some(e)
        }
        _ => _rt::invalid_enum_discriminant(),
      } }
    }
  }
  _MySubtask { _unused: core::marker::PhantomData }.call((binding,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn reveal(s: &Secret,) -> _rt::String{
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    i32,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (&'a Secret, );
      type Results = _rt::String;
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked((2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>())
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/secrets@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]reveal"]
          fn call(_: i32, _: *mut u8, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: i32, _: *mut u8, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,_results) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe {  }
      }
      unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
        unsafe {  }
      }
      unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
        unsafe {  ParamsLower((_lower0).handle() as i32,) }
      }
      unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
        unsafe { let l0 = *_ptr.add(0).cast::<*mut u8>();
        let l1 = *_ptr.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len2 = l1;
        let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);

        _rt::string_lift(bytes2) }
      }
    }
    _MySubtask { _unused: core::marker::PhantomData }.call((s,)).await
  }
}

}


#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod outbound {
  #[used]
  #[doc(hidden)]
  static __FORCE_SECTION_REF: fn() =
  super::super::super::__link_custom_section_describing_imports;

  use super::super::super::_rt;
  pub type Header = super::super::super::myedge::runtime::types::Header;
  #[derive(Clone)]
  pub struct Request {
    pub method: _rt::String,
    pub uri: _rt::String,
    pub headers: _rt::Vec::<Header>,
    pub body: _rt::Vec::<u8>,
  }
  impl ::core::fmt::Debug for Request {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      f.debug_struct("Request").field("method", &self.method).field("uri", &self.uri).field("headers", &self.headers).field("body", &self.body).finish()
    }
  }
  #[derive(Clone)]
  pub struct Response {
    pub status: u16,
    pub headers: _rt::Vec::<Header>,
    pub body: _rt::Vec::<u8>,
  }
  impl ::core::fmt::Debug for Response {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      f.debug_struct("Response").field("status", &self.status).field("headers", &self.headers).field("body", &self.body).finish()
    }
  }
  #[allow(unused_unsafe, clippy::all)]
  #[allow(async_fn_in_trait)]
  pub async fn fetch(req: Request,) -> Response{
    unsafe {

      #[derive(Copy, Clone)]
      struct ParamsLower(
      *mut u8,
      );
      unsafe impl Send for ParamsLower {}


      use wit_bindgen::rt::async_support::Subtask as _Subtask;
      struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
      #[allow(unused_parens)]
      unsafe impl<'a> _Subtask for _MySubtask<'a> {

        type Params = (Request, );
        type Results = Response;
        type ParamsLower = ParamsLower;
        fn abi_layout(&mut self) -> ::core::alloc::Layout {
          unsafe {
            ::core::alloc::Layout::from_size_align_unchecked((13*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>())
          }
        }

        fn results_offset(&mut self) -> usize { (8*::core::mem::size_of::<*const u8>()) }

        unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/outbound@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[async-lower]fetch"]
            fn call(_: *mut u8, _: *mut u8, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn call(_: *mut u8, _: *mut u8, ) -> i32 { unreachable!() }

          unsafe { call(_params.0,_results) as u32 }
        }

        unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
          unsafe { let l0 = *_params.0.add(0).cast::<*mut u8>();
          let l1 = *_params.0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l0, l1, 1);
          let l2 = *_params.0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l3 = *_params.0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l2, l3, 1);
          let l4 = *_params.0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l5 = *_params.0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l4;
          let len10 = l5;
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            {
              let l6 = *base.add(0).cast::<*mut u8>();
              let l7 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l6, l7, 1);
              let l8 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l9 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l8, l9, 1);
            }
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let l11 = *_params.0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l12 = *_params.0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base13 = l11;
          let len13 = l12;
          _rt::cabi_dealloc(base13, len13 * 1, 1);
        }
      }
      unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
        unsafe { let l0 = *_params.0.add(0).cast::<*mut u8>();
        let l1 = *_params.0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
        let l2 = *_params.0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l3 = *_params.0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l2, l3, 1);
        let l4 = *_params.0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l5 = *_params.0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l4;
        let len10 = l5;
        for i in 0..len10 {
          let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let l6 = *base.add(0).cast::<*mut u8>();
            let l7 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l6, l7, 1);
            let l8 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l9 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l8, l9, 1);
          }
        }
        _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l11 = *_params.0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l12 = *_params.0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base13 = l11;
        let len13 = l12;
        _rt::cabi_dealloc(base13, len13 * 1, 1);
      }
    }
    unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
      let _param_ptr = unsafe { _ptr.add(0) };
      unsafe { let Request{ method:method0, uri:uri0, headers:headers0, body:body0, } = _lower0;
      let vec1 = (method0.into_bytes()).into_boxed_slice();
      let ptr1 = vec1.as_ptr().cast::<u8>();
      let len1 = vec1.len();
      ::core::mem::forget(vec1);
      *_param_ptr.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len1;
      *_param_ptr.add(0).cast::<*mut u8>() = ptr1.cast_mut();
      let vec2 = (uri0.into_bytes()).into_boxed_slice();
      let ptr2 = vec2.as_ptr().cast::<u8>();
      let len2 = vec2.len();
      ::core::mem::forget(vec2);
      *_param_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
      *_param_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
      let vec6 = headers0;
      let len6 = vec6.len();
      let layout6 = _rt::alloc::Layout::from_size_align(vec6.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result6, _cleanup6) = wit_bindgen::rt::Cleanup::new(layout6);if let Some(cleanup) = _cleanup6 { cleanup.forget(); }
      for (i, e) in vec6.into_iter().enumerate() {
        let base = result6.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let super::super::super::myedge::runtime::types::Header{ name:name3, value:value3, } = e;
          let vec4 = (name3.into_bytes()).into_boxed_slice();
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          ::core::mem::forget(vec4);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
          *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
          let vec5 = (value3.into_bytes()).into_boxed_slice();
          let ptr5 = vec5.as_ptr().cast::<u8>();
          let len5 = vec5.len();
          ::core::mem::forget(vec5);
          *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
          *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
        }
      }
      *_param_ptr.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
      *_param_ptr.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result6;
      let vec7 = <_ as Into<_rt::Vec<_>>>::into(body0).into_boxed_slice();
      let ptr7 = vec7.as_ptr().cast::<u8>();
      let len7 = vec7.len();
      ::core::mem::forget(vec7);
      *_param_ptr.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
      *_param_ptr.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
    }
    ParamsLower(_ptr,)
  }
  unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
    unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u16>());
    let l1 = *_ptr.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l2 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base9 = l1;
    let len9 = l2;
    let mut result9 = _rt::Vec::with_capacity(len9);
    for i in 0..len9 {
      let base = base9.add(i * (4*::core::mem::size_of::<*const u8>()));
      let e9 = {
        let l3 = *base.add(0).cast::<*mut u8>();
        let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
        let l6 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l7 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len8 = l7;
        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

        super::super::super::myedge::runtime::types::Header{
          name: _rt::string_lift(bytes5),
          value: _rt::string_lift(bytes8),
        }
      };
      result9.push(e9);
    }
    _rt::cabi_dealloc(base9, len9 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    let l10 = *_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l11 = *_ptr.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len12 = l11;

    Response{
      status: l0 as u16,
      headers: result9,
      body: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l10.cast(), len12, len12)),
    } }
  }
}
_MySubtask { _unused: core::marker::PhantomData }.call((req,)).await
}
}

}


#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod log {
  #[used]
  #[doc(hidden)]
  static __FORCE_SECTION_REF: fn() =
  super::super::super::__link_custom_section_describing_imports;

  use super::super::super::_rt;
  #[allow(unused_unsafe, clippy::all)]
  #[allow(async_fn_in_trait)]
  pub async fn info(message: _rt::String,) -> (){
    unsafe {

      #[derive(Copy, Clone)]
      struct ParamsLower(
      *mut u8, usize,
      );
      unsafe impl Send for ParamsLower {}


      use wit_bindgen::rt::async_support::Subtask as _Subtask;
      struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
      #[allow(unused_parens)]
      unsafe impl<'a> _Subtask for _MySubtask<'a> {

        type Params = (_rt::String, );
        type Results = ();
        type ParamsLower = ParamsLower;
        fn abi_layout(&mut self) -> ::core::alloc::Layout {
          unsafe {
            ::core::alloc::Layout::from_size_align_unchecked(0, 1)
          }
        }

        fn results_offset(&mut self) -> usize { 0 }

        unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "myedge:runtime/log@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[async-lower]info"]
            fn call(_: *mut u8, _: usize, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn call(_: *mut u8, _: usize, ) -> i32 { unreachable!() }

          unsafe { call(_params.0,_params.1,) as u32 }
        }

        unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
          unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
        }
      }
      unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
      }
    }
    unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
      unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
      let ptr0 = vec0.as_ptr().cast::<u8>();
      let len0 = vec0.len();
      ::core::mem::forget(vec0);
      ParamsLower(ptr0.cast_mut(), len0,) }
    }
    unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

    }
  }
  _MySubtask { _unused: core::marker::PhantomData }.call((message,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn warn(message: _rt::String,) -> (){
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    *mut u8, usize,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (_rt::String, );
      type Results = ();
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked(0, 1)
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/log@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]warn"]
          fn call(_: *mut u8, _: usize, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: *mut u8, _: usize, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,_params.1,) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
      }
    }
    unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
      unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
    }
  }
  unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
    unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
    let ptr0 = vec0.as_ptr().cast::<u8>();
    let len0 = vec0.len();
    ::core::mem::forget(vec0);
    ParamsLower(ptr0.cast_mut(), len0,) }
  }
  unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

  }
}
_MySubtask { _unused: core::marker::PhantomData }.call((message,)).await
}
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub async fn error(message: _rt::String,) -> (){
  unsafe {

    #[derive(Copy, Clone)]
    struct ParamsLower(
    *mut u8, usize,
    );
    unsafe impl Send for ParamsLower {}


    use wit_bindgen::rt::async_support::Subtask as _Subtask;
    struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
    #[allow(unused_parens)]
    unsafe impl<'a> _Subtask for _MySubtask<'a> {

      type Params = (_rt::String, );
      type Results = ();
      type ParamsLower = ParamsLower;
      fn abi_layout(&mut self) -> ::core::alloc::Layout {
        unsafe {
          ::core::alloc::Layout::from_size_align_unchecked(0, 1)
        }
      }

      fn results_offset(&mut self) -> usize { 0 }

      unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "myedge:runtime/log@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[async-lower]error"]
          fn call(_: *mut u8, _: usize, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn call(_: *mut u8, _: usize, ) -> i32 { unreachable!() }

        unsafe { call(_params.0,_params.1,) as u32 }
      }

      unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
        unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
      }
    }
    unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
      unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
    }
  }
  unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
    unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
    let ptr0 = vec0.as_ptr().cast::<u8>();
    let len0 = vec0.len();
    ::core::mem::forget(vec0);
    ParamsLower(ptr0.cast_mut(), len0,) }
  }
  unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {

  }
}
_MySubtask { _unused: core::marker::PhantomData }.call((message,)).await
}
}

}

}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }

  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }

  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }

  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub use alloc_crate::alloc;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }

  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }

  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }

  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_worker_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_worker_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_worker_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.51.0:myedge:runtime@0.1.0:worker:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1316] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa7\x09\x01A\x02\x01\
A\x15\x01B\x07\x01r\x02\x04names\x05values\x04\0\x06header\x03\0\0\x01p\x01\x01r\
\x03\x06methods\x03uris\x07headers\x02\x04\0\x0crequest-head\x03\0\x03\x01r\x02\x06\
status{\x07headers\x02\x04\0\x0dresponse-head\x03\0\x05\x03\0\x1amyedge:runtime/\
types@0.1.0\x05\0\x02\x03\0\0\x0crequest-head\x02\x03\0\0\x0dresponse-head\x01B\x18\
\x02\x03\x02\x01\x01\x04\0\x0crequest-head\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0d\
response-head\x03\0\x02\x04\0\x0dincoming-body\x03\x01\x04\0\x0doutgoing-body\x03\
\x01\x01i\x04\x01r\x02\x04head\x01\x04body\x06\x04\0\x07request\x03\0\x07\x01i\x05\
\x01r\x02\x04head\x03\x04body\x09\x04\0\x08response\x03\0\x0a\x01h\x04\x01p}\x01\
k\x0d\x01C\x02\x04self\x0c\x03maxw\0\x0e\x04\0\x1a[method]incoming-body.read\x01\
\x0f\x01h\x05\x01C\x02\x04self\x10\x05chunk\x0d\x01\0\x04\0\x1b[method]outgoing-\
body.write\x01\x11\x01C\x01\x04self\x10\x01\0\x04\0\x1c[method]outgoing-body.fin\
ish\x01\x12\x01@\0\0\x09\x04\0\x11new-outgoing-body\x01\x13\x03\0\x19myedge:runt\
ime/http@0.1.0\x05\x03\x01B\x0f\x04\0\x09namespace\x03\x01\x01i\0\x01k\x01\x01@\x01\
\x07bindings\0\x02\x04\0\x0eopen-namespace\x01\x03\x01h\0\x01p}\x01k\x05\x01C\x02\
\x02ns\x04\x03keys\0\x06\x04\0\x03get\x01\x07\x01kw\x01C\x04\x02ns\x04\x03keys\x05\
value\x05\x0bttl-seconds\x08\x01\0\x04\0\x03put\x01\x09\x01C\x02\x02ns\x04\x03ke\
ys\x01\0\x04\0\x06delete\x01\x0a\x03\0\x17myedge:runtime/kv@0.1.0\x05\x04\x01B\x08\
\x04\0\x06secret\x03\x01\x01i\0\x01k\x01\x01@\x01\x07bindings\0\x02\x04\0\x0bope\
n-secret\x01\x03\x01h\0\x01C\x01\x01s\x04\0s\x04\0\x06reveal\x01\x05\x03\0\x1cmy\
edge:runtime/secrets@0.1.0\x05\x05\x02\x03\0\0\x06header\x01B\x0a\x02\x03\x02\x01\
\x06\x04\0\x06header\x03\0\0\x01p\x01\x01p}\x01r\x04\x06methods\x03uris\x07heade\
rs\x02\x04body\x03\x04\0\x07request\x03\0\x04\x01r\x03\x06status{\x07headers\x02\
\x04body\x03\x04\0\x08response\x03\0\x06\x01C\x01\x03req\x05\0\x07\x04\0\x05fetc\
h\x01\x08\x03\0\x1dmyedge:runtime/outbound@0.1.0\x05\x07\x01B\x04\x01@\x01\x07me\
ssages\x01\0\x04\0\x04info\x01\0\x04\0\x04warn\x01\0\x04\0\x05error\x01\0\x03\0\x18\
myedge:runtime/log@0.1.0\x05\x08\x02\x03\0\x01\x07request\x03\0\x07request\x03\0\
\x09\x02\x03\0\x01\x08response\x03\0\x08response\x03\0\x0b\x01C\x01\x03req\x0a\0\
\x0c\x04\0\x06handle\x01\x0d\x04\0\x1bmyedge:runtime/worker@0.1.0\x04\0\x0b\x0c\x01\
\0\x06worker\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.244.0\x10wit-bindgen-rust\x060.51.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

