receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "[::]:4317"
      http:
        endpoint: "[::]:4318"

processors:
  batch:
    timeout: 1s

connectors:
  spanmetrics:
    namespace: oden
    histogram:
      explicit:
        buckets: [10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2.5s, 5s]
    dimensions:
      - name: http.request.method
      - name: http.response.status_code
      - name: oden.project_id
      - name: oden.deployment_id

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "[::]:9464"

extensions:
  health_check:
    endpoint: "[::]:13133"
  zpages:
    endpoint: "[::]:55679"

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
